package functions

import "sort"

// RemoveDuplicateValues - remove duplicated values inside an array
// from https://www.geeksforgeeks.org/how-to-remove-duplicate-values-from-slice-in-golang/
func RemoveDuplicateValues(intSlice []string) []string {
	keys := make(map[string]bool)
	list := []string{}

	// If the key(values of the slice) is not equal
	// to the already present value in new slice (list)
	// then we append it. else we jump on another element.
	for _, entry := range intSlice {
		if _, value := keys[entry]; !value {
			keys[entry] = true
			list = append(list, entry)
		}
	}
	return list
}

func RemoveDuplicateIntValues(intSlice []int) []int {
	keys := make(map[int]bool)
	list := []int{}

	// If the key(values of the slice) is not equal
	// to the already present value in new slice (list)
	// then we append it. else we jump on another element.
	for _, entry := range intSlice {
		if _, value := keys[entry]; !value {
			keys[entry] = true
			list = append(list, entry)
		}
	}
	return list
}

// Diff - compare two arrays and keep the values that do not coincide
// from https://play.golang.org/p/zgbCunAHyM5
func Diff(a []string, b []string) []string {
	// Turn b into a map
	var m map[string]bool
	m = make(map[string]bool, len(b))
	for _, s := range b {
		m[s] = false
	}
	// Append values from the longest slice that don't exist in the map
	var diff []string
	for _, s := range a {
		if _, ok := m[s]; !ok {
			diff = append(diff, s)
			continue
		}
		m[s] = true
	}
	// Sort the resulting slice
	sort.Strings(diff)
	return diff
}

// Unique values inside an array
// From: https://www.golangprograms.com/remove-duplicate-values-from-slice.html
func Unique(intSlice []string) []string {
	keys := make(map[string]bool)
	list := []string{}
	for _, entry := range intSlice {
		if _, value := keys[entry]; !value {
			keys[entry] = true
			list = append(list, entry)
		}
	}
	return list
}

// to convert the library language codes to Wikidata codes
func CheckLanguagesCodes(code string) string {

	listOfLanguages := map[string]string{
		"aar": "aa",
		"abk": "ab",
		"ave": "ae",
		"afr": "af",
		"aka": "ak",
		"amh": "am",
		"arg": "an",
		"ara": "ar",
		"asm": "as",
		"ava": "av",
		"aym": "ay",
		"aze": "az",
		"bak": "ba",
		"bel": "be",
		"bul": "bg",
		"bis": "bi",
		"bam": "bm",
		"ben": "bn",
		"bod": "bo",
		"bre": "br",
		"bos": "bs",
		"cat": "ca",
		"che": "ce",
		"cha": "ch",
		"cos": "co",
		"cre": "cr",
		"ces": "cs",
		"chu": "cu",
		"chv": "cv",
		"cym": "cy",
		"cze": "cz",
		"dan": "da",
		"ger": "de",
		"div": "dv",
		"dzo": "dz",
		"ewe": "ee",
		"ell": "el",
		"eng": "en",
		"epo": "eo",
		"spa": "es",
		"est": "et",
		"eus": "eu",
		"fas": "fa",
		"ful": "ff",
		"fin": "fi",
		"fij": "fj",
		"fao": "fo",
		"fre": "fr",
		"fry": "fy",
		"gle": "ga",
		"gla": "gd",
		"glg": "gl",
		"grn": "gn",
		"guj": "gu",
		"glv": "gv",
		"hau": "ha",
		"heb": "he",
		"hin": "hi",
		"hmo": "ho",
		"hrv": "hr",
		"hat": "ht",
		"hun": "hu",
		"hye": "hy",
		"her": "hz",
		"ina": "ia",
		"ind": "id",
		"ile": "ie",
		"ibo": "ig",
		"iii": "ii",
		"ipk": "ik",
		"ido": "io",
		"isl": "is",
		"ita": "it",
		"iku": "iu",
		"jpn": "ja",
		"jav": "jv",
		"kat": "ka",
		"kon": "kg",
		"kik": "ki",
		"kua": "kj",
		"kaz": "kk",
		"kal": "kl",
		"khm": "km",
		"kan": "kn",
		"kor": "ko",
		"kau": "kr",
		"kas": "ks",
		"kur": "ku",
		"kom": "kv",
		"cor": "kw",
		"kir": "ky",
		"lat": "la",
		"ltz": "lb",
		"lug": "lg",
		"lim": "li",
		"lin": "ln",
		"lao": "lo",
		"lit": "lt",
		"lub": "lu",
		"lav": "lv",
		"mlg": "mg",
		"mah": "mh",
		"mri": "mi",
		"mkd": "mk",
		"mal": "ml",
		"mon": "mn",
		"mar": "mr",
		"msa": "ms",
		"mlt": "mt",
		"mya": "my",
		"nau": "na",
		"nob": "nb",
		"nde": "nd",
		"nep": "ne",
		"ndo": "ng",
		"nld": "nl",
		"nno": "nn",
		"nor": "no",
		"nbl": "nr",
		"nav": "nv",
		"nya": "ny",
		"oci": "oc",
		"oji": "oj",
		"orm": "om",
		"ori": "or",
		"oss": "os",
		"pan": "pa",
		"pli": "pi",
		"pol": "pl",
		"pus": "ps",
		"por": "pt",
		"que": "qu",
		"roh": "rm",
		"run": "rn",
		"ron": "ro",
		"rus": "ru",
		"kin": "rw",
		"san": "sa",
		"srd": "sc",
		"snd": "sd",
		"sme": "se",
		"sag": "sg",
		"sin": "si",
		"slk": "sk",
		"slv": "sl",
		"smo": "sm",
		"sna": "sn",
		"som": "so",
		"sqi": "sq",
		"srp": "sr",
		"ssw": "ss",
		"sot": "st",
		"sun": "su",
		"swe": "sv",
		"swa": "sw",
		"tam": "ta",
		"tel": "te",
		"tgk": "tg",
		"tha": "th",
		"tir": "ti",
		"tuk": "tk",
		"tgl": "tl",
		"tsn": "tn",
		"ton": "to",
		"tur": "tr",
		"tso": "ts",
		"tat": "tt",
		"twi": "tw",
		"tah": "ty",
		"uig": "ug",
		"ukr": "uk",
		"urd": "ur",
		"uzb": "uz",
		"ven": "ve",
		"vie": "vi",
		"vol": "vo",
		"wln": "wa",
		"wol": "wo",
		"xho": "xh",
		"yid": "yi",
		"yor": "yo",
		"zha": "za",
		"zho": "zh",
		"zul": "zu",
	}
	return listOfLanguages[code]
}

// to convert the librarycountry codes to Wikidata codes
func CheckCountryName(code string) string {

	listOfCountries := map[string]string{
		"AF": "Afeganistão",
		"ZA": "África do Sul",
		"AL": "Albânia",
		"DD": "Alemã, República Democrática",
		"DE": "Alemanha, República Federal da",
		"AD": "Andorra",
		"AO": "Angola",
		"AI": "Anguilla",
		"AQ": "Antártica",
		"AG": "Antígua e Barbuda",
		"AN": "Antilhas Holandesas",
		"SA": "Arábia Saudita",
		"DZ": "Argélia",
		"AR": "Argentina",
		"AW": "Aruba",
		"AU": "Austrália",
		"AT": "Austria",
		"BS": "Baamas",
		"BH": "Bahrein",
		"BD": "Bangladesh",
		"BB": "Barbados",
		"BE": "Bélgica",
		"BZ": "Belize",
		"BJ": "Benin",
		"BM": "Bermudas",
		"BY": "Bielorússia, R.S.S. da",
		"BO": "Bolívia",
		"BW": "Botswana",
		"BV": "Bouvet, Ilha",
		"BR": "Brasil",
		"BN": "Brunei Darussalam",
		"BG": "Bulgária",
		"BF": "Burkina Faso",
		"BI": "Burundi",
		"BT": "Butão",
		"CV": "Cabo Verde",
		"KY": "Caimans, Ilhas",
		"CM": "Camarões",
		"CA": "Canadá",
		"QA": "Catar",
		"CF": "Centroafricana, República",
		"TD": "Chade",
		"CS": "Checoslováquia",
		"CL": "Chile",
		"CN": "China, República Popular da",
		"CY": "Chipre",
		"CX": "Christmas, Ilha",
		"CC": "Cocos (Keeling), Ilha dos",
		"CO": "Colômbia",
		"KM": "Comores",
		"CG": "Congo",
		"CK": "Cook, Ilhas",
		"KR": "Coreia, República da",
		"KP": "Coreia, Rep. Pop. Democrática da",
		"CI": "Costa do Marfim",
		"CR": "Costa Rica",
		"CU": "Cuba",
		"DK": "Dinamarca",
		"DJ": "Djibouti",
		"DO": "Dominicana, República",
		"DM": "Dominica",
		"EG": "Egipto",
		"SV": "El Salvador",
		"AE": "Emiratos Arabes Unidos (EAU)",
		"EC": "Equador",
		"ES": "Espanha",
		"US": "Estados Unidos da América (EUA)",
		"ET": "Etiópia",
		"FK": "Falklands (Malvinas), Ilhas",
		"FO": "Feroe, Ilhas",
		"FJ": "Fidji",
		"PH": "Filipinas",
		"FI": "Finlândia",
		"FR": "França",
		"GA": "Gabão",
		"GM": "Gâmbia",
		"GH": "Gana",
		"GI": "Gibraltar",
		"GD": "Granada",
		"GR": "Grécia",
		"GL": "Gronelândia",
		"GP": "Guadalupe",
		"GU": "Guam",
		"GT": "Guatemala",
		"GY": "Guiana",
		"GF": "Guiana Francesa",
		"GN": "Guiné",
		"GW": "Guiné-Bissau",
		"GQ": "Guiné Equatorial",
		"HT": "Haiti",
		"HM": "Heard e McDonald, Ilhas",
		"HN": "Honduras",
		"HK": "Hong-Kong",
		"HU": "Hungria",
		"YE": "Iemen",
		"YD": "Iemen Democrático",
		"UM": "Ilhas Menores Exteriores (Estados Unidos)",
		"VG": "Ilhas Virgens (Britânicas)",
		"VI": "Ilhas Virgens (E.U.)",
		"IN": "India",
		"ID": "Indonésia",
		"IR": "Irão, República Islâmica do",
		"IQ": "Iraque",
		"IE": "Irlanda",
		"IS": "Islândia",
		"IL": "Israel",
		"IT": "Itália",
		"JM": "Jamaica",
		"JP": "Japão",
		"JO": "Jordânia",
		"YU": "Jugoslávia",
		"KH": "Kampuchea Democrático",
		"KI": "Kiribati",
		"KW": "Koweit",
		"LA": "Laos, Rep. Democrática Popular",
		"LS": "Lesotho",
		"LB": "Líbano",
		"LR": "Libéria",
		"LY": "Líbia, Jamahiriya Arabe",
		"LI": "Liechtenstein",
		"LU": "Luxemburgo",
		"MO": "Macau",
		"MG": "Madagascar",
		"MY": "Malásia",
		"MW": "Malawi",
		"MV": "Maldivas",
		"ML": "Mali",
		"MT": "Malta",
		"MP": "Marianas do Norte, Ilhas",
		"MA": "Marrocos",
		"MH": "Marshall, Ilhas",
		"MQ": "Martinica",
		"MU": "Maurícias",
		"MR": "Mauritânia",
		"MX": "México",
		"FM": "Micronésia",
		"MZ": "Moçambique",
		"MC": "Mónaco",
		"MN": "Mongólia",
		"MS": "Montserrat",
		"MM": "Myanmar",
		"NA": "Namíbia",
		"NR": "Nauru",
		"NP": "Nepal",
		"NI": "Nicarágua",
		"NE": "Niger",
		"NG": "Nigéria",
		"NU": "Niue",
		"NF": "Norfolk, Ilha",
		"NO": "Noruega",
		"NC": "Nova Caledónia",
		"NZ": "Nova Zelândia",
		"IO": "Oceano Índico, Territ. Britânico do",
		"OM": "Oman",
		"NL": "Países Baixos",
		"PW": "Palau",
		"PA": "Panamá",
		"PK": "Paquistão",
		"PG": "Papuásia Nova Guiné",
		"PY": "Paraguai",
		"PE": "Perú",
		"PN": "Pitcairn",
		"PF": "Polinésia Francesa",
		"PL": "Polónia",
		"PR": "Porto Rico",
		"PT": "Portugal",
		"KE": "Quénia",
		"GB": "Reino Unido",
		"RE": "Reunião",
		"RO": "Roménia",
		"RW": "Ruanda",
		"EH": "Saara Ocidental",
		"SB": "Salomão, Ilhas",
		"WS": "Samoa",
		"AS": "Samoa Americana",
		"SH": "Santa Helena",
		"LC": "Santa Lúcia",
		"SM": "São Marino",
		"PM": "São Pedro e Miquelon",
		"ST": "São Tomé e Príncipe",
		"VC": "São Vicente e Granadinas",
		"SN": "Senegal",
		"SL": "Serra Leoa",
		"KN": "St. Kitts e Nevis",
		"SC": "Seychelles",
		"SG": "Singapura",
		"SY": "Síria, República årabe da",
		"SO": "Somália",
		"LK": "Sri Lanka",
		"SZ": "Suazilândia",
		"SD": "Sudão",
		"SE": "Suécia",
		"CH": "Suíça",
		"SR": "Suriname",
		"SJ": "Svalbard e Ilha Jan Mayen",
		"TH": "Tailândia",
		"TW": "Taiwan (Formosa)",
		"TZ": "Tanzânia, República Unida da",
		"TF": "Territórios Franceses do Sul",
		"TP": "Timor Leste",
		"TG": "Togo",
		"TK": "Tokelau",
		"TO": "Tonga",
		"TT": "Trindade e Tobago",
		"TN": "Tunísia",
		"TC": "Turks e Caiques, Ilhas",
		"TR": "Turquia",
		"TV": "Tuvalu",
		"UA": "Ucrânia, R.S.S. da",
		"UG": "Uganda",
		"SU": "URSS",
		"UY": "Uruguai",
		"VU": "Vanuatu",
		"VA": "Vaticano, Estado da Cidade do (Santa Sé)",
		"VE": "Venezuela",
		"VN": "Vietname",
		"WF": "Wallis e Futuna, Ilhas",
		"ZR": "Zaire",
		"ZM": "Zâmbia",
		"ZW": "Zimbabwe",
		"NT": "Zona Neutra (entre a Arábia Saudita e o Iraque)",
	}

	return listOfCountries[code]
}
